name:                            Teardown AWS Lambda

on:                              [workflow_dispatch]

jobs:

  teardown:
    name:                        Teardown Lambda
    runs-on:                     ubuntu-latest

    steps:

      - name:                    Checkout
        uses:                    actions/checkout@v2.3.3

      - name:                    Configure AWS Credentials
        uses:                    aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            eu-west-2

      - name:                    Setup Terraform environment
        uses:                    hashicorp/setup-terraform@v1.2.0
        with:
          terraform_version:     0.13.0

      - name:                    Terraform init
        run:                     |
          cd terraform
          terraform init -backend-config=backend-config/lab

      - name:                    Terraform destroy
        run:                     |
          cd terraform
          terraform destroy -var lambda_pkg_filename=../bin/function.zip -auto-approve
